apiVersion: 1
datasources:
- access: proxy
  isDefault: true
  jsonData:
    requestUrl: ${DEEPFLOW_REQUEST_URL}
    traceUrl: ${DEEPFLOW_TRACEURL}
  name: DeepFlow
  type: deepflow-querier-datasource
  uid: DeepFlow
  url: null
- jsonData:
    port: 9000
    server: ${CLICKHOUSE_SERVER}
    username: ${CLICKHOUSE_USER}
  name: DeepFlow ClickHouse
  secureJsonData:
    password: ${CLICKHOUSE_PASSWORD}
  type: grafana-clickhouse-datasource
  uid: DeepFlow ClickHouse
- database: deepflow
  jsonData:
    connMaxLifetime: 14400
    maxIdleConns: 5
    maxOpenConns: 5
  name: DeepFlow MySQL
  secureJsonData:
    password: ${MYSQL_PASSWORD}
  type: mysql
  uid: DeepFlow MySQL
  url: ${MYSQL_URL}
  user: ${MYSQL_USER}
- name: DeepFlow-Tempo
  uid: DeepFlow-Tempo
  type: tempo
  access: proxy
  url: ${DEEPFLOW_REQUEST_URL}
  jsonData: {}